from typing import Any, Optional
from datetime import datetime
from decimal import Decimal
from pydantic import BaseModel, Field, field_validator
from app.core.showtime.domain.entities.showtime import ShowtimeBase
from app.core.showtime.domain.enums import ShowtimeLanguage, ShowtimeType
from app.core.showtime.domain.entities.showtime_seat import ShowtimeSeatBase


class ShowtimeCreate(ShowtimeBase):
    """Schema for creating a new Showtime. No ID or timestamps."""

    pass


class ShowtimeUpdate(BaseModel):
    """Schema for updating an existing Showtime. All fields optional for partial updates."""

    id: int = Field(
        ..., description="The ID of the showtime to update."
    )  # Required for update
    movie_id: Optional[int] = None
    theater_id: Optional[int] = None
    price: Optional[Decimal] = None
    start_time: Optional[datetime] = None
    end_time: Optional[datetime] = None
    type: Optional[ShowtimeType] = None
    language: Optional[ShowtimeLanguage] = None

    @field_validator("start_time")
    @classmethod
    def validate_start_time_timezone(cls, v: Any):
        if v.tzinfo is None:
            raise ValueError("start_time must include time zone information")
        return v

    @field_validator("end_time")
    @classmethod
    def validate_end_time_timezone(cls, v: Any):
        if v is not None and v.tzinfo is None:
            raise ValueError("end_time must include time zone information")
        return v


class ShowtimeSeatCreate(ShowtimeSeatBase):
    """
    Schema for creating a new ShowtimeSeat.
    'id' and timestamps are not included as they are typically generated by the database.
    """

    pass


class ShowtimeSeatUpdate(BaseModel):
    """
    Schema for updating an existing ShowtimeSeat.
    All fields are optional for partial updates.
    """

    id: int = Field(
        ..., description="The unique identifier of the showtime seat to update."
    )
    showtime_id: Optional[int] = Field(
        None, description="The ID of the showtime this seat belongs to."
    )
    theater_seat_id: Optional[int] = Field(
        None, description="The ID of the specific theater seat."
    )
    taken_at: Optional[datetime] = Field(
        None, description="Timestamp when the seat was taken/booked."
    )
    transaction_id: Optional[int] = Field(
        None, description="The ID of the transaction associated with this booking."
    )
    user_id: Optional[int] = Field(
        None, description="The ID of the user who took this seat."
    )
