DELETE FROM movies
WHERE title IN (
    'The Dark Knight',
    'Superbad',
    'The Shawshank Redemption',
    'The Notebook',
    'Inception',
    'Gone Girl',
    'Hero',
    'Bridesmaids',
    'Parasite',
    'Casablanca',
    'Dune',
    'Psycho',
    'Black Panther',
    'The Lego Movie',
    'The Social Network',
    'La La Land',
    'Blade Runner 2049',
    'The Silence of the Lambs',
    'Mission: Impossible - Fallout',
    'Dr. Strangelove',
    '2001: A Space Odyssey',
    'When Harry Met Sally',
    'Black Swan',
    'Spider-Man: Into the Spider-Verse',
    'Schindler''s List',
    'Deadpool',
    'The Lord of the Rings: The Fellowship of the Ring',
    'Fargo',
    'Whiplash',
    'Avengers: Endgame',
    'The Departed',
    'Spirited Away',
    'Alien',
    'Lady Bird',
    'Kingsman: The Secret Service',
    'The Grand Budapest Hotel',
    'Rocky',
    'The Matrix',
    'Eternal Sunshine of the Spotless Mind',
    'Get Out'
);