from enum import Enum

class ShowtimeType(str, Enum):
    TRADITIONAL_2D = 'TRADITIONAL_2D'
    TRADITIONAL_3D = 'TRADITIONAL_3D'
    IMAX_2D = 'IMAX_2D'
    IMAX_3D = 'IMAX_3D'
    _4D = '4D'
    _4DX = '4DX'
    VIP_2D = 'VIP_2D'
    VIP_3D = 'VIP_3D'


class ShowtimeLanguage(str, Enum):
    ORIGINAL_ENGLISH = "ORIGINAL_ENGLISH"
    ORIGINAL_SPANISH = "ORIGINAL_SPANISH"
    ORIGINAL_JAPANESE = "ORIGINAL_JAPANESE"
    ORIGINAL_KOREAN = "ORIGINAL_KOREAN"

    DUBBED_ENGLISH = "DUBBED_ENGLISH"
    DUBBED_SPANISH = "DUBBED_SPANISH"
