from pydantic import Field, BaseModel
from typing import Optional
from app.theater.domain.enums import SeatType
from app.theater.domain.seat import TheaterSeatBase


class TheaterSeatCreate(TheaterSeatBase):
    """
    Schema for creating a new TheaterSeat.
    'id' and timestamps are not included as they are typically generated by the database.
    """

class TheaterSeatUpdate(BaseModel):
    """
    Schema for updating an existing TheaterSeat.
    All fields are optional for partial updates.
    """
    theater_id: Optional[int] = Field(None, description="The ID of the theater this seat belongs to.")
    seat_row: Optional[str] = Field(None, max_length=5, description="The row identifier of the seat (e.g., 'A', 'AA', 'SEC1').")
    seat_number: Optional[int] = Field(None, gt=0, description="The number of the seat within its row.")
    seat_type: Optional[SeatType] = Field(None, description="The classification type of the seat (e.g., STANDARD, VIP, ACCESSIBLE).")
    is_active: Optional[bool] = Field(None, description="Indicates if the seat is currently active and usable.")
